//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class productos
    {
        public int id_produto { get; set; }
        public string nombre_producto { get; set; }
        public long precio { get; set; }
        public int producto_cantidad { get; set; }
        public string descripcion_producto { get; set; }
        public int id_provedor { get; set; }
    
        public virtual provedores provedores { get; set; }
    }
}
